name: Vadama
on: [workflow_dispatch, push] # Runs when you push code or click 'Run' manually

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS (Unsigned)
        run: |
          flutter build ios --release --no-codesign
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r FlutterIpaExport.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: FlutterIpaExport.ipa
