name: Build iOS IPA
on: [workflow_dispatch, push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Install Pods
        run: |
          cd ios
          # Ensure there is a project to link to
          if [ ! -d "Runner.xcodeproj" ]; then echo "Error: Runner.xcodeproj not found!"; exit 1; fi
          
          pod install --repo-update || (pod repo update && pod install)
          cd ..



      - name: Build iOS (Unsigned)
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r FlutterIpaExport.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: FlutterIpaExport.ipa
